# Generated by Django 4.1.4 on 2023-01-20 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FridgeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FridgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('category', models.IntegerField(choices=[(1, 'Fruits'), (2, 'Vegetables'), (3, 'Legumes'), (4, 'Grains & Cereals'), (5, 'Bread'), (6, 'Meat & Eggs'), (7, 'Fish & Seafood'), (8, 'Dairy products'), (9, 'Beverages'), (10, 'Desserts, Snacks & Sweets'), (11, 'Prepared food'), (12, 'Instant food'), (13, 'Spices'), (14, 'Condiments')])),
                ('quantity', models.IntegerField()),
                ('quantityType', models.IntegerField(choices=[(1, 'piece(s)'), (2, 'ml'), (3, 'l'), (4, 'mg'), (5, 'g'), (6, 'kg')], default=1)),
                ('expirationDate', models.DateField(blank=True, default=None, null=True)),
                ('openedDate', models.DateField(blank=True, null=True)),
                ('expiringSoon', models.BooleanField(blank=True, default=False)),
                ('expired', models.BooleanField(blank=True, default=False)),
                ('fridgeList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge', to='fridge.fridgelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fridge Entries',
            },
        ),
        migrations.CreateModel(
            name='BuyListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('category', models.IntegerField(choices=[(1, 'Fruits'), (2, 'Vegetables'), (3, 'Legumes'), (4, 'Grains & Cereals'), (5, 'Bread'), (6, 'Meat & Eggs'), (7, 'Fish & Seafood'), (8, 'Dairy products'), (9, 'Beverages'), (10, 'Desserts, Snacks & Sweets'), (11, 'Prepared food'), (12, 'Instant food'), (13, 'Spices'), (14, 'Condiments')])),
                ('quantity', models.IntegerField()),
                ('quantityType', models.IntegerField(choices=[(1, 'piece(s)'), (2, 'ml'), (3, 'l'), (4, 'mg'), (5, 'g'), (6, 'kg')], default=1)),
                ('fridgeList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.fridgelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Buy List Entries',
            },
        ),
        migrations.CreateModel(
            name='BuyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('fridgeList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.fridgelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
