# Generated by Django 4.1.5 on 2023-01-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('pw', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='FridgeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.account')),
            ],
        ),
        migrations.CreateModel(
            name='FridgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('quantity', models.IntegerField()),
                ('quantityType', models.CharField(max_length=60)),
                ('expirationDate', models.DateField()),
                ('openedDate', models.DateField(blank=True)),
                ('expiringSoon', models.BooleanField()),
                ('expired', models.BooleanField()),
                ('fridgeList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.fridgelist')),
            ],
            options={
                'verbose_name_plural': 'Fridge Entries',
            },
        ),
        migrations.CreateModel(
            name='BuyListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('quantity', models.IntegerField()),
                ('quantityType', models.CharField(max_length=60)),
                ('buyList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.fridgelist')),
            ],
            options={
                'verbose_name_plural': 'Buy List Entries',
            },
        ),
        migrations.CreateModel(
            name='BuyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('fridgeList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridge.fridgelist')),
            ],
        ),
    ]
