# Generated by Django 4.1.5 on 2023-01-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_remove_fridgelist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridgeentry',
            name='fridgeList',
        ),
    ]
