# Generated by Django 4.1.5 on 2023-01-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0003_remove_fridgeentry_fridgelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeentry',
            name='fridgeList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fridge', to='fridge.fridgelist'),
            preserve_default=False,
        ),
    ]
