# Generated by Django 4.1.5 on 2023-01-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_fridgeentry_fridgelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeentry',
            name='expired',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='fridgeentry',
            name='expiringSoon',
            field=models.BooleanField(blank=True),
        ),
    ]
