# Generated by Django 4.1.5 on 2023-01-08 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_alter_fridgeentry_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeentry',
            name='openedDate',
            field=models.DateField(blank=True, default=datetime.date(2023, 1, 8)),
        ),
    ]
