# Generated by Django 4.1.5 on 2023-01-08 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0006_alter_fridgeentry_openeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeentry',
            name='expirationDate',
            field=models.DateField(default=datetime.date(2023, 1, 8)),
        ),
        migrations.AlterField(
            model_name='fridgeentry',
            name='openedDate',
            field=models.DateField(blank=True),
        ),
    ]
