# Generated by Django 4.1.5 on 2023-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0007_alter_fridgeentry_expirationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeentry',
            name='expired',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='fridgeentry',
            name='expiringSoon',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='fridgeentry',
            name='openedDate',
            field=models.DateField(null=True),
        ),
    ]
