# Generated by Django 4.1.5 on 2023-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0008_alter_fridgeentry_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeentry',
            name='openedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
