# Generated by Django 4.1.5 on 2023-01-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0009_alter_fridgeentry_openeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeentry',
            name='category',
            field=models.IntegerField(choices=[(1, 'Fruits'), (2, 'Vegetables'), (3, 'Legumes'), (4, 'Grains & Cereals'), (5, 'Bread'), (6, 'Meat & Eggs'), (7, 'Fish & Seafood'), (8, 'Dairy products'), (9, 'Beverages'), (10, 'Desserts, Snacks & Sweets'), (11, 'Prepared food'), (12, 'Instant food'), (13, 'Spices')]),
        ),
        migrations.AlterField(
            model_name='fridgeentry',
            name='quantityType',
            field=models.IntegerField(choices=[(1, 'piece(s)'), (2, 'ml'), (3, 'l'), (4, 'mg'), (5, 'g'), (6, 'kg')], default=1),
        ),
    ]
