# Generated by Django 4.1.5 on 2023-01-13 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0011_rename_buylist_buylistentry_fridgelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeentry',
            name='expirationDate',
            field=models.DateField(blank=True, default=datetime.date(2023, 1, 13), null=True),
        ),
    ]
