# Generated by Django 4.1.5 on 2023-01-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0012_alter_fridgeentry_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeentry',
            name='expirationDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
