# Generated by Django 4.1.5 on 2023-01-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0013_alter_fridgeentry_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylistentry',
            name='category',
            field=models.IntegerField(choices=[(1, 'Fruits'), (2, 'Vegetables'), (3, 'Legumes'), (4, 'Grains & Cereals'), (5, 'Bread'), (6, 'Meat & Eggs'), (7, 'Fish & Seafood'), (8, 'Dairy products'), (9, 'Beverages'), (10, 'Desserts, Snacks & Sweets'), (11, 'Prepared food'), (12, 'Instant food'), (13, 'Spices'), (14, 'Condiments')]),
        ),
        migrations.AlterField(
            model_name='fridgeentry',
            name='category',
            field=models.IntegerField(choices=[(1, 'Fruits'), (2, 'Vegetables'), (3, 'Legumes'), (4, 'Grains & Cereals'), (5, 'Bread'), (6, 'Meat & Eggs'), (7, 'Fish & Seafood'), (8, 'Dairy products'), (9, 'Beverages'), (10, 'Desserts, Snacks & Sweets'), (11, 'Prepared food'), (12, 'Instant food'), (13, 'Spices'), (14, 'Condiments')]),
        ),
    ]
